pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }
    agent any
        stages {
            stage('PreBuild') {
                parallel {
                    stage('Dependencies') {
                        steps {
                            sh 'cd src && yarn'
                        }
                    }
                }
            }
            stage('Build') {
                steps {
                    sh 'cd src && yarn build'
                }
                post {
                    success {
                        echo 'Build succeeded.'
                    }
                    failure {
                        echo 'Build failed.'
                    }
                }
            }
            stage('Lint') {
                steps {
                    sh 'cd src && yarn lint'
                }
            }
            stage('Test') {
                steps {
                    sh 'cd src && yarn test'
                }
            }
        }
    }


